[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
[[redirects]]
    force: true
    from = "/image/*"
    to = "/image/:id"
    status = 200
[build]
  command = "CI=false npm run build"
  functions = "netlify/functions"
  publish = "build"